### ISSUE TITLE
Node transaction incentive

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/business-epics#13]
With the SNR (Signum Network Reward) a bonus was introduced to Signum Node operators for keeping up the Signum Network. The system is well established and we will continue with this setup.

However, based on this setup we would like to introduce another level of decentralization and give a reward for node operators if those nodes are used for transaction generation. 

**How does this work ?**
If a user is generating a transaction with a node (local or remote) the node will check if on the P2P.myPlatform or a new config parameter (to discuss)  in its config a valid Signum account address and will attach this account to the transaction.

When the transaction gets processed a part of the fee is paid to this account instead to the miner - if no account is attached all fees go to the miner.

**Adjusting the minimum fee**
In CIP-03, the minimum fee was changed from 1 Signa to 0.00735 Signa.
To give a fair amount to the node operator we would change the minimum fee to 0.01 Signa and pay 26.5% to the attached account. This way, if you run your own node you will still pay the previous minimum value of 0.00735 Signa. Recalling that CIP-31 introduces a “per byte” fee basis and that will still apply.

We would achieve two goals with this - getting more human friendly looking minimum fees and also being able to pay a good portion to the node operator´s account.

This change would require a hard fork.

**Comment by maxbrito500** [comment]
Talking from experience running bitcoin nodes, I think this is a really good idea. First because of the incentives to motivate more people to run nodes from their machines, and second because it helps a lot with popularity since many of those node operators will be bringing more people to run transactions.

In lightning node you bid for transaction fees, and that isn't really working out super well. On Signum, today we see a heavy concentration of nodes around EU and USA without reaching other regions so much. Perhaps a portion of the transactions can be routed to the geographically closest node operator?

Don't if possible/feasible from a technical view. However, it would help to motivate people running nodes across diverse areas of the globe and reap the benefits from helping grow the community where they live.

Maybe the calculations could be done on 24 hours period. Fees would then be distributed to the active nodes equally and then allocate a portion for the geographic transactions.

**Comment by dudleyperkins** [comment]
I think it's a good idea, it may have some downsides tho, 2 things i instantly think of:
1. after all it's a raise for the majority of users, by that i mean everybody without (the possibility to run) a node
2. it could lead to a race where node operators trying to catch as many people as they can - leading people away from signum.network nodes

While the first one is not a big problem cause the fee is still low enough, the second one is kind of the opposite of what i would've expected.
e.g. on the signum explorer the P2P.myAddress was once displayed as a functional URL so you could navigate directly to the node. And i think it was a good move to only display the "official" signum.network nodes there. After all these are the same ones that phoenix uses (you can't even change the node on android to your own node).

I run a node so this step wouldn't affect me. In conclusion i would see it as a way to keep SNR going. Hoping most users would use signum nodes and generate income for running offical wallet-infrastructure and constantly funding SNR payments to other nodes. Nodes that are there to keep the network alive/wide spread and not just for catching people/getting more fees.

**Comment by frankTheTank72** [comment]
Will be introduced with https://github.com/signum-network/SIPs/blob/master/SIP/sip-35.md
