### ISSUE TITLE
Token enhancement

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/business-epics#5]
We need addtional token features to be more up to date:

- Flexible in number of tokens
- Cap yes/no
- can be mint or burned by creator

**Comment by shefass** [comment]
"Flexible in number of tokens" it is main way haw tokens are hacked in other chains: by releasing many more and dumping them, or by taking control of project if tokens have some voting power.

Maybe we can have several versions of tokens with different functionality. And because of blockchain nature probably easier to add new version of tokens, then improving old ones. 

After smart contracts will see tokens, it can control it (cap, mint or burned and etc.), like in ETH you can have different tokens with custom functions.

**Comment by frankTheTank72** [comment]
Will be introduced with https://github.com/signum-network/SIPs/blob/master/SIP/sip-33.md
